CoreDemo/Areas/Admin/Controllers/WriterController.cs
using Microsoft.AspNetCore.Mvc;

namespace CoreDemo.Areas.Admin.Controllers
{
	[Area("Admin")]

	public class WriterController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreDemo/Controllers/WriterController.cs
using BussinesLayer.Concrete;
using BussinesLayer.ValidationRules;
using CoreDemo.Models;
using DataAccesLayer.concrete;
using DataAccesLayer.EntityFramework;
using EntityLayer.concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace CoreDemo.Controllers
{
    
    public class WriterController : Controller
    {
        WriterManager vm=new WriterManager(new EfWriterRepository());
        [Authorize]
        public IActionResult Index()
        {
            var usermail = User.Identity.Name;
            ViewBag.v=usermail;
            return View();
        }

        public IActionResult WriterProfile()
        {
            return View();
        }

        public IActionResult WriterMail()
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }
        public PartialViewResult writernavbar()
        {
            return PartialView();
        }

        public PartialViewResult footerPartial()
        {
            {
                return PartialView();
            }
        }
        [HttpGet]
        public IActionResult WriterEditProfile() {
            var usermail = User.Identity.Name;
            Context c=new Context();
            var writerID = c.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();
            var values = vm.TGetbyId(writerID);
            return View(values);
        }
        
        [HttpPost]
        public IActionResult WriterEditProfile(Writer p)
        {
            WriterValidatör wl=new WriterValidatör();
            FluentValidation.Results.ValidationResult validationResult = wl.Validate(p);

            if (validationResult.IsValid)
            {
                p.WriterStatus = true;
                vm.Update(p); 
                
                return RedirectToAction("Index", "Dashboard");

            }
            else
            {
                foreach (var item in validationResult.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult WriterAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult WriterAdd(AddProfileImage p)
        {
            Writer w=new Writer();
            if (p.writerImage != null) {
                var extension = Path.GetExtension(p.writerImage.FileName);
                var newimagename=Guid.NewGuid()+extension;
                var location=Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/WriterImageFiles/"+newimagename);
                var stream=new FileStream(location,FileMode.Create);
                p.writerImage.CopyTo(stream);
                w.writerImage=newimagename;
            
            }
            w.WriterMail = p.WriterMail;
            w.WriterAbout = p.WriterAbout;
            w.WriterName = p.WriterName;
            w.WriterPassword = p.WriterPassword;
            w.WriterStatus= p.WriterStatus;
            vm.TAdd(w);
            return View();
        }
    }
}

CoreDemo/Views/Writer/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Test</h1>

CoreDemo/Views/Writer/WriterAdd.cshtml
@model Writer
@{
    ViewData["Title"] = "WriterAdd";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic form elements</h4>
            <p class="card-description">Yazar Profil Bilgileri Düzenleme </p>
            <form class="forms-sample" asp-action="EditProfile" asp-controller="Writer" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="exampleInputName1">Name</label>
                    <input type="text" class="form-control" id="WriterName" value="@Model.WriterName" name="WriterName" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail3">Email</label>
                    <input type="email" class="form-control" id="WriterMail" value="@Model.WriterMail" name="WriterMail" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword4">Şifre</label>
                    <input type="password" class="form-control" name="WriterPassword" id="WriterPassword" placeholder="Password">
                </div>
                <div class="mb-3">
                    <label for="blogImage" class="form-label">Blog Image</label>
                    <input type="file" class="form-control" id="blogImage" name="writerImage" accept="image/*">
                </div>
                <div class="form-group">
                    <label for="exampleTextarea1">Yazar Hakkında</label>
                    <textarea class="form-control" id="WriterAbout" name="WriterAbout" rows="4">@Model.WriterAbout</textarea>
                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Güncelle</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>

CoreDemo/Views/Writer/WriterEditProfile.cshtml
@model Writer
@{
    ViewData["Title"] = "WriterEditProfile";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic form elements</h4>
            <p class="card-description">Yazar Profil Bilgileri Düzenleme </p>
            <form class="forms-sample" asp-action="EditProfile" asp-controller="Writer" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="exampleInputName1">Name</label>
                    <input type="text" class="form-control" id="WriterName" value="@Model.WriterName" name="WriterName" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail3">Email</label>
                    <input type="email" class="form-control" id="WriterMail" value="@Model.WriterMail" name="WriterMail" placeholder="Email">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword4">Şifre</label>
                    <input type="password" class="form-control" name="WriterPassword" id="WriterPassword" placeholder="Password">
                </div>
                <div class="mb-3">
                    <label for="blogImage" class="form-label">Blog Image</label>
                    <input type="file" class="form-control" id="blogImage" name="writerImage" accept="image/*">
                </div>
                <div class="form-group">
                    <label for="exampleTextarea1">Yazar Hakkında</label>
                    <textarea class="form-control" id="WriterAbout" name="WriterAbout" rows="4">@Model.WriterAbout</textarea>
                </div>
                <button type="submit" class="btn btn-gradient-primary mr-2">Güncelle</button>
                <button class="btn btn-light">İptal</button>
            </form>
        </div>
    </div>
</div>

CoreDemo/Views/Writer/WriterMail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

CoreDemo/Views/Writer/footerPartial.cshtml
<footer class="footer">
    <div class="container-fluid clearfix">
        <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2024</span>
        <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Yazar Panelşi <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Writer Panel </a> from Bootstrapdash.com</span>
    </div>
</footer>

CoreDemo/Views/Writer/writernavbar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="../../assets/images/faces/face1.jpg" alt="profile">
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">Yazar Adı Soyadı</span>
                    <span class="text-secondary text-small">Project Manager</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Dashboard/Index">
                <span class="menu-title">Dashboard</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterProfile">
                <span class="menu-title">Profilim</span>
                <i class="mdi mdi-contacts menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogListByWriter">
                <span class="menu-title">Bloglarım</span>
                <i class="mdi mdi-format-list-bulleted menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/BlogAdd">
                <span class="menu-title">Yeni Blog</span>
                <i class="mdi mdi-chart-bar menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterMessage">
                <span class="menu-title">Mesajlar</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Notification/AllNotification">
                <span class="menu-title">Bildirimler</span>
                <i class="mdi mdi-message menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Blog/Index">
                <span class="menu-title">Siteye Git</span>
                <i class="mdi mdi-car menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Writer/WriterProfile">
                <span class="menu-title">Ayarlar</span>
                <i class="mdi mdi-settings menu-icon"></i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/Login/WriterLogOut">
                <span class="menu-title">Çıkış Yap</span>
                <i class="mdi mdi-logout menu-icon"></i>
            </a>
        </li>




    </ul>
</nav>